# Список пользователей
GET http://51.250.21.224/api/users/

###
GET http://51.250.21.224/api/users/subscriptions/?page=1&limit=6&recipes_limit=3
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

###
GET http://51.250.21.224/api/users/subscriptions/?page=1&limit=6&recipes_limit=3
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

###
# Создать пользователя
POST http://51.250.21.224/api/users/
content-type: application/json

{
    "email": "Gagr@gaga.ru",
    "username": "Gagaasd",
    "first_name": "Gaasd",
    "last_name": "AGsdsd",
    "password": "FFFwhdsdgwh2313"
}

###
# Пользователь
GET http://51.250.21.224/api/users/4/
content-type: application/json

###
GET http://51.250.21.224/api/users/me/
content-type: application/json

###
POST http://51.250.21.224/api/auth/token/login/
content-type: application/json

{
    "email": "admin@admin.ru",
    "password": "admin"
}


###
POST http://51.250.21.224/api/users/set_password/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

{
    "new_password": "FFFwdsfshdsdgwh2313",
    "current_password": "FFFwhdsdgwh2313"
}

###
GET http://51.250.21.224/api/recipes/
content-type: application/json

###
GET http://51.250.21.224/api/recipes/36/

###
POST http://51.250.21.224/api/recipes/
content-type: application/json
Authorization: Token 06b1e26f8bd131629e6ce31dbaded2046f7c7b1a

{
    "name": "dsdgfdsgsdf",
    "text": "text_text",
    "cooking_time": 5,
    "ingredients": [
        {
            "id": 1,
            "amount": 232
        },
        {
            "id": 2,
            "amount": 1
        }
    ],
    "tags": [
        1,
        2
    ]
}

###
GET http://51.250.21.224/api/tags/

###
GET http://51.250.21.224/api/tags/454453/

###
GET http://51.250.21.224/api/tags/1/


###
GET http://51.250.21.224/api/recipes/download_shopping_cart/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

###
GET http://51.250.21.224/api/recipes/37/shopping_cart/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

###
DELETE http://51.250.21.224/api/recipes/37/shopping_cart/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

###
GET http://51.250.21.224/api/recipes/37/favorite/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8


###
DELETE  http://51.250.21.224/api/recipes/37/favorite/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8


###
# Неправильно работает
GET http://51.250.21.224/api/users/subscriptions/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

###
GET http://51.250.21.224/api/users/3/subscribe/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

### 
GET http://51.250.21.224/api/ingredients/


###
GET http://51.250.21.224/api/ingredients/1/


### 
GET http://51.250.21.224/subscriptions