# Список пользователей
GET http://51.250.21.224/api/users/

###
GET http://51.250.21.224/api/users/subscriptions/?page=1&limit=6&recipes_limit=3
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

###
GET http://51.250.21.224/api/users/subscriptions/?page=1&limit=6&recipes_limit=3
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

###
# Создать пользователя
POST http://51.250.21.224/api/users/
content-type: application/json

{
    "email": "Gagr@gaga.ru",
    "username": "Gagaasd",
    "first_name": "Gaasd",
    "last_name": "AGsdsd",
    "password": "FFFwhdsdgwh2313"
}

###
# Пользователь
GET http://51.250.21.224/api/users/4/
content-type: application/json

###
GET http://51.250.21.224/api/users/me/
content-type: application/json

###
POST http://51.250.21.224/api/auth/token/login/
content-type: application/json

{
    "email": "admin@admin.ru",
    "password": "admin"
}


###
POST http://51.250.21.224/api/users/set_password/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

{
    "new_password": "FFFwdsfshdsdgwh2313",
    "current_password": "FFFwhdsdgwh2313"
}

###
GET http://51.250.21.224/api/recipes/
content-type: application/json

###
GET http://51.250.21.224/api/recipes/36/
###
POST http://51.250.21.224/api/recipes/
content-type: application/json
Authorization: Token aad4577f33764f26e4eb3a4a4f16a675a911fac9

{
    "name": "dsdg2323fdsgsdf1",
    "text": "text_text1",
    "cooking_time": 5,
    "tags": [
        1
    ],
    "ingredients": [
        {       
        "id": 2188,
        "amount": 232
        },
        {
        "id": 2187,
        "amount": 1
        }
    ],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOAAAAB/CAMAAADBwz5FAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAGUExURQAAAAAAAKVnuc8AAAACdFJOU/8A5bcwSgAAAAlwSFlzAAAOwwAADsMBx2+oZAAAAj9JREFUeF7t3Nt6hCAMBODd93/p6spXJaCEJMCAmcuVkPlrD3f9fBePA2ePA2ePA2ePA2ePA2ePA2ePA2ePA2ePA2dPA+CHnTDQNEPfYHA27QDxLRqce8IndoEAXmJuRANusSUCAm2JkEBLIijQjggLtCJ2Bx5/DZKEp3EsiPorQkNuwhTNzUM9UXdBtpQiP2V8o/Z+8XxaxSzx1cotkum4QKP8lhxbVLsqh8+tfXLs02ysme1rO3MoheEOanYYZHuLwgasmbG4X44GgiLFAeEXzj6hRW2dwmkQ3J6zSZXx6SjKuwu5luFXuz+HpdtC+jCNd4fgeFuSShzjzQlA3pZMq8343DX/FNN32/bJmH2E6rsvtr/IvJP7GUZKzTLP5wKWhckBphkl5W6UmE4g+1jl4jPJBLSP1y46RCewfQIhGUD3MQteTq0JvBxbFHj+Ml0V+B8HgmV5YHVDB6LFgSQORIsDSeh5eKEDSRyIFgeSJOfRhQ4kcSBaHEjiQLSogejC5YG1/V4IRBc6MM4bgeDC1YG15V4JhBY6kCR/Hli4OrC62UuBuEIH0rwVCCtcHVhf67VAUKEhEFNoCYQUrg4UVHoawRMaA/GE1kA4oQPTFEbAhPZALKGkTHEGSejATMozQMI2QCBhIyCMUNTDgXswhLIWvCkI4epAYQfmGICwLXC8UFqAPTda2Bw4WCjeXjE4VNgDOFTYBThQKN9cN/n0f02aphdQs0kTxdbq0SHCnsARQs1KwWz/H0T5wu/3D9RhbVhHdGiPAAAAAElFTkSuQmCC"
}

###
POST http://51.250.21.224/api/recipes/
content-type: application/json
Authorization: Token aad4577f33764f26e4eb3a4a4f16a675a911fac9

{"name":"Гусь","image":"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEBLAEsAAD//gA7Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2NjIpLCBxdWFsaXR5ID0gODUK/9","tags":[1],"cooking_time":"3423","text":"efewf","ingredients":[{"id":388,"amount":"1"}]}

###
POST http://51.250.21.224/api/recipes/
content-type: application/json
Authorization: Token aad4577f33764f26e4eb3a4a4f16a675a911fac9

{
    "name": "dsdgfdsgsdf",
    "text": "text_text",
    "cooking_time": 5,
    "ingredients": [
        {
            "id": 1,
            "amount": 232
        },
        {
            "id": 2,
            "amount": 1
        }
    ],
    "tags": [
        1,
        2
    ],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOAAAAB/CAMAAADBwz5FAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAGUExURQAAAAAAAKVnuc8AAAACdFJOU/8A5bcwSgAAAAlwSFlzAAAOwwAADsMBx2+oZAAAAj9JREFUeF7t3Nt6hCAMBODd93/p6spXJaCEJMCAmcuVkPlrD3f9fBePA2ePA2ePA2ePA2ePA2ePA2ePA2ePA2ePA2dPA+CHnTDQNEPfYHA27QDxLRqce8IndoEAXmJuRANusSUCAm2JkEBLIijQjggLtCJ2Bx5/DZKEp3EsiPorQkNuwhTNzUM9UXdBtpQiP2V8o/Z+8XxaxSzx1cotkum4QKP8lhxbVLsqh8+tfXLs02ysme1rO3MoheEOanYYZHuLwgasmbG4X44GgiLFAeEXzj6hRW2dwmkQ3J6zSZXx6SjKuwu5luFXuz+HpdtC+jCNd4fgeFuSShzjzQlA3pZMq8343DX/FNN32/bJmH2E6rsvtr/IvJP7GUZKzTLP5wKWhckBphkl5W6UmE4g+1jl4jPJBLSP1y46RCewfQIhGUD3MQteTq0JvBxbFHj+Ml0V+B8HgmV5YHVDB6LFgSQORIsDSeh5eKEDSRyIFgeSJOfRhQ4kcSBaHEjiQLSogejC5YG1/V4IRBc6MM4bgeDC1YG15V4JhBY6kCR/Hli4OrC62UuBuEIH0rwVCCtcHVhf67VAUKEhEFNoCYQUrg4UVHoawRMaA/GE1kA4oQPTFEbAhPZALKGkTHEGSejATMozQMI2QCBhIyCMUNTDgXswhLIWvCkI4epAYQfmGICwLXC8UFqAPTda2Bw4WCjeXjE4VNgDOFTYBThQKN9cN/n0f02aphdQs0kTxdbq0SHCnsARQs1KwWz/H0T5wu/3D9RhbVhHdGiPAAAAAElFTkSuQmCC"
}

###
GET http://51.250.21.224/api/tags/

###
GET http://51.250.21.224/api/tags/454453/

###
GET http://51.250.21.224/api/tags/1/


###
GET http://51.250.21.224/api/recipes/download_shopping_cart/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

###
GET http://51.250.21.224/api/recipes/37/shopping_cart/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

###
DELETE http://51.250.21.224/api/recipes/37/shopping_cart/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

###
GET http://51.250.21.224/api/recipes/37/favorite/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8


###
DELETE  http://51.250.21.224/api/recipes/37/favorite/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8


###
# Неправильно работает
GET http://51.250.21.224/api/users/subscriptions/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

###
GET http://51.250.21.224/api/users/3/subscribe/
content-type: application/json
Authorization: Token dbff2f5c8030e92908bb5712894f5c448539e6f8

### 
GET http://51.250.21.224/api/ingredients/


###
GET http://51.250.21.224/api/ingredients/1/


### 
GET http://51.250.21.224/subscriptions