

# Список пользователей
GET http://127.0.0.1:8000/api/users/

###
# Создать пользователя
POST http://127.0.0.1:8000/api/users/
content-type: application/json

{
    "email": "Gagr@gaga.ru",
    "username": "Gagaasd",
    "first_name": "Gaasd",
    "last_name": "AGsdsd",
    "password": "FFFwhdsdgwh2313"
}

###
# Пользователь
GET http://127.0.0.1:8000/api/users/4/
content-type: application/json

###
# личгая страница
GET http://127.0.0.1:8000/api/users/me/

###
# личгая страница
GET http://127.0.0.1:8000/api/users/me/
content-type: application/json
Authorization: Token a833a4ad163dd459e05e52a6e5f1821ed95ea7d2

###
# Получение токена
POST http://127.0.0.1:8000/api/auth/token/login/
content-type: application/json

{
    "email": "admin@admin.ru",
    "password": "admin"
}


###
# Смена пароля
POST http://127.0.0.1:8000/api/users/set_password/
content-type: application/json
Authorization: Token a833a4ad163dd459e05e52a6e5f1821ed95ea7d2

{
    "new_password": "FFFwdsfshdsdgwh2313",
    "current_password": "FFFwhdsdgwh2313"
}

###
# Рецепты
GET http://127.0.0.1:8000/api/recipes/
content-type: application/json
###
# рецепты
GET http://127.0.0.1:8000/api/recipes/
content-type: application/json
Authorization: Token a833a4ad163dd459e05e52a6e5f1821ed95ea7d2

###
# Рецепты в избранном
GET http://127.0.0.1:8000/api/recipes/?is_favorited=True
content-type: application/json
Authorization: Token a833a4ad163dd459e05e52a6e5f1821ed95ea7d2

###
# Рецепты
GET http://127.0.0.1:8000/api/recipes/
content-type: application/json

###
# Рецепт
GET http://127.0.0.1:8000/api/recipes/47/
content-type: application/json
Authorization: Token a833a4ad163dd459e05e52a6e5f1821ed95ea7d2

###
# Рецепт
GET http://127.0.0.1:8000/api/recipes/

###
GET http://127.0.0.1:8000/api/ingredients/

###
GET http://127.0.0.1:8000/api/ingredients/?name=кар

###
GET http://127.0.0.1:8000/api/recipes/?page=1&limit=6&tags=breakfast


###
# Создание рецепта
POST http://127.0.0.1:8000/api/recipes/
content-type: application/json
Authorization: Token 14493d0c7af7e8716f51515e414c139386c377d6

{
    "name": "dsdg2323fdsgsdf1",
    "text": "text_text1",
    "cooking_time": 5,
    "ingredients": [
        {
            "id": 1,
            "amount": 232
        },
        {
            "id": 2,
            "amount": 1
        }
    ],
    "tags": [
        3
    ],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOAAAAB/CAMAAADBwz5FAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAGUExURQAAAAAAAKVnuc8AAAACdFJOU/8A5bcwSgAAAAlwSFlzAAAOwwAADsMBx2+oZAAAAj9JREFUeF7t3Nt6hCAMBODd93/p6spXJaCEJMCAmcuVkPlrD3f9fBePA2ePA2ePA2ePA2ePA2ePA2ePA2ePA2ePA2dPA+CHnTDQNEPfYHA27QDxLRqce8IndoEAXmJuRANusSUCAm2JkEBLIijQjggLtCJ2Bx5/DZKEp3EsiPorQkNuwhTNzUM9UXdBtpQiP2V8o/Z+8XxaxSzx1cotkum4QKP8lhxbVLsqh8+tfXLs02ysme1rO3MoheEOanYYZHuLwgasmbG4X44GgiLFAeEXzj6hRW2dwmkQ3J6zSZXx6SjKuwu5luFXuz+HpdtC+jCNd4fgeFuSShzjzQlA3pZMq8343DX/FNN32/bJmH2E6rsvtr/IvJP7GUZKzTLP5wKWhckBphkl5W6UmE4g+1jl4jPJBLSP1y46RCewfQIhGUD3MQteTq0JvBxbFHj+Ml0V+B8HgmV5YHVDB6LFgSQORIsDSeh5eKEDSRyIFgeSJOfRhQ4kcSBaHEjiQLSogejC5YG1/V4IRBc6MM4bgeDC1YG15V4JhBY6kCR/Hli4OrC62UuBuEIH0rwVCCtcHVhf67VAUKEhEFNoCYQUrg4UVHoawRMaA/GE1kA4oQPTFEbAhPZALKGkTHEGSejATMozQMI2QCBhIyCMUNTDgXswhLIWvCkI4epAYQfmGICwLXC8UFqAPTda2Bw4WCjeXjE4VNgDOFTYBThQKN9cN/n0f02aphdQs0kTxdbq0SHCnsARQs1KwWz/H0T5wu/3D9RhbVhHdGiPAAAAAElFTkSuQmCC"
}

###
# Теги
GET http://127.0.0.1:8000/api/tags/

###
# Несуществующий тэг
GET http://127.0.0.1:8000/api/tags/454453/

###
# Тэг
GET http://127.0.0.1:8000/api/tags/1/

###
# Лист рецептов в карте покупок
GET http://127.0.0.1:8000/api/recipes/?is_in_shopping_cart=true
content-type: application/json
Authorization: Token a833a4ad163dd459e05e52a6e5f1821ed95ea7d2


###
# Скачать карту покупок
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
content-type: application/json
Authorization: Token 14493d0c7af7e8716f51515e414c139386c377d6

###
# Добавить в карту покупок
GET http://127.0.0.1:8000/api/recipes/1/shopping_cart/
content-type: application/json
Authorization: Token 14493d0c7af7e8716f51515e414c139386c377d6

###
# Удалить из карты покупок
DELETE http://127.0.0.1:8000/api/recipes/44/shopping_cart/
content-type: application/json
Authorization: Token a833a4ad163dd459e05e52a6e5f1821ed95ea7d2

###
# Добавить в избранное
GET http://127.0.0.1:8000/api/recipes/47/favorite/
content-type: application/json
Authorization: Token a833a4ad163dd459e05e52a6e5f1821ed95ea7d2


###
# Удалить из избранного
DELETE http://127.0.0.1:8000/api/recipes/47/favorite/
content-type: application/json
Authorization: Token a833a4ad163dd459e05e52a6e5f1821ed95ea7d2


###
# Подписки
GET http://127.0.0.1:8000/api/users/?is_following=True
content-type: application/json
Authorization: Token a833a4ad163dd459e05e52a6e5f1821ed95ea7d2


###
GET  http://127.0.0.1:8000/api/users/subscriptions/?page=1&limit=6&recipes_limit=3
content-type: application/json
Authorization: Token a833a4ad163dd459e05e52a6e5f1821ed95ea7d2


###
# Список подписок
GET http://127.0.0.1:8000/api/users/subscriptions/
content-type: application/json
Authorization: Token a833a4ad163dd459e05e52a6e5f1821ed95ea7d2

###
# Подписка
GET http://127.0.0.1:8000/api/users/9/subscribe/
content-type: application/json
Authorization: Token a833a4ad163dd459e05e52a6e5f1821ed95ea7d2

###
# Отписка
DELETE  http://127.0.0.1:8000/api/users/8/subscribe/
content-type: application/json
Authorization: Token a833a4ad163dd459e05e52a6e5f1821ed95ea7d2

### 
# Ингредиенты
GET http://127.0.0.1:8000/api/ingredients/


###
# Ингредиент
GET http://127.0.0.1:8000/api/ingredients/1/

