# Generated by Django 3.2 on 2021-11-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211130_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='008000', max_length=20, verbose_name='Цвет'),
        ),
    ]
