# Generated by Django 3.2 on 2021-11-30 17:29

import recipes.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=recipes.fields.ColorField(default='008000', max_length=20, verbose_name='Цвет'),
        ),
    ]
