# Generated by Django 3.2 on 2021-12-01 18:16

from django.db import migrations, models
import recipes.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20211130_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=recipes.fields.ColorField(default='#008000', max_length=20, verbose_name='Цвет HEX'),
        ),
        migrations.AddConstraint(
            model_name='favoritesource',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Уникальный список рецептов в избранном'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Уникальные рецепты в списке покупок'),
        ),
    ]
