# Generated by Django 3.2 on 2021-12-01 18:25

from django.db import migrations
import recipes.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20211201_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=recipes.fields.ColorField(choices=[('#0000FF', 'Синий'), ('#FFA500', 'Оранжевый'), ('#008000', 'Зеленый'), ('#800080', 'Фиолетовый'), ('#FFFF00', 'Желтый'), ('#000000', 'Чёрный'), ('#ff0000', 'Красный'), ('#42aaff', 'Голубой')], default='#008000', max_length=20, verbose_name='Цвет HEX'),
        ),
    ]
