# Generated by Django 3.2 on 2021-12-07 08:28

import recipes.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0012_auto_20211204_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favoritesource',
            new_name='Favorite',
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=recipes.fields.ColorField(choices=[('#0000FF', 'Синий'), ('#FFA500', 'Оранжевый'), ('#008000', 'Зеленый'), ('#800080', 'Фиолетовый'), ('#FFFF00', 'Желтый'), ('#000000', 'Чёрный'), ('#ff0000', 'Красный'), ('#42aaff', 'Голубой')], default='#0000FF', max_length=7, verbose_name='Цвет HEX'),
        ),
    ]
