# Generated by Django 3.2 on 2021-12-08 10:03

import recipes.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20211207_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=recipes.fields.ColorField(choices=[('#0000FF', 'Синий'), ('#FFA500', 'Оранжевый'), ('#008000', 'Зеленый'), ('#800080', 'Фиолетовый'), ('#FFFF00', 'Желтый'), ('#000000', 'Чёрный'), ('#ff0000', 'Красный'), ('#42aaff', 'Голубой')], default='#42aaff', max_length=7, verbose_name='Цвет HEX'),
        ),
    ]
